task: cifar10
model: res18_cifar
dataset: cifar10
device: cuda
# federated learning
fl:
  optimizer: sgd
  optimizer_args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  K: 100
  C: 0.1
  B: 64
  E: 1
  eta: 1
  epochs: 200
  val_batch_size: 128
poisoned_fl:
  optimizer: sgd
  optimizer_args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  K: 100
  C: 0.1
  B: 64
  E: 1
  eta: 0.1
  epochs: 100
  val_batch_size: 128
# local training
local:
  optimizer: sgd
  optimizer_args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  batch_size: 128
  epochs: 200
  val_batch_size: 128
# constrain and scale attack
constrain_scale:
  mode: semantic_pattern
  single_shot: False
  attack_epochs: [0]
  pixel_pattern:
    attack_ratio: 0.1
    locs: [[0,0],[0,1],[0,2],[1,0],[1,1],[1,2],[2,0],[2,1],[2,2]]
    fill: [2.5141, 2.5968, 2.7537]
    swap_label: 2
    poison_lr: 0.05
    weight_decay: 0.005
    retrain_epochs: 2
    batch_size: 64
    test_batch_size: 128
    poison_per_batch: 20
    scale_weight: 1
  semantic_pattern:
    attack_ratio: 0.1
    poison_train: [30696,33105,33615,33907,36848,40713,41706]
    poison_test: [330,568,3934,12336,30560]
    swap_label: 2
    poison_lr: 0.05
    weight_decay: 0.005
    retrain_epochs: 2
    batch_size: 64
    test_batch_size: 128
    poison_per_batch: 1
    scale_weight: 1

dba:
  attack_ratio: 0.08
  pixel_pattern_1: [[0,0],[0,1],[0,2],[0,3],[0,4],[0,5]]
  pixel_pattern_2: [[0,9],[0,10],[0,11],[0,12],[0,13],[0,14]]
  pixel_pattern_3: [[4,0],[4,1],[4,2],[4,3],[4,4],[4,5]]
  pixel_pattern_4: [[4,9],[4,10],[4,11],[4,12],[4,13],[4,14]]
  fill: [2.5141, 2.5968, 2.7537]
  swap_label: 2
  poison_lr: 0.05
  weight_decay: 0.005
  retrain_epochs: 2
  batch_size: 64
  test_batch_size: 128
  poison_per_batch: 5
  scale_weight: 1
    
edgecase:
  single_shot: False
  attack_epochs: [0]
  attack_ratio: 0.1
  swap_label: 9
  poison_lr: 0.05
  weight_decay: 0.005
  retrain_epochs: 2
  batch_size: 64
  test_batch_size: 128
  poison_data_num: 100
  pure_data_num: 400
  scale_weight: 1

pgd:
  single_shot: False
  attack_epochs: [0]
  attack_ratio: 0.1
  swap_label: 9
  poison_lr: 0.05
  weight_decay: 0.005
  retrain_epochs: 4
  batch_size: 64
  test_batch_size: 128
  poison_data_num: 100
  pure_data_num: 400
  scale_weight: 1
  eps: 1

untargeted_poisoning:
  flip:
    0: 2
    1: 9
    5: 3